version: '3.8'
services:
  app:
    container_name: node_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/dbname
    healthcheck:
      test: ["CMD", "curl", "-f", "<http://localhost:5000/health>"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: